package com.telcel.gam.siev.util;

import java.io.File;
import java.io.IOException;

import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;
import org.jdom2.Namespace;

public class ReadXMLFile {

    public static String getResponseCreditCheck() {
    	StringBuilder respCredCheck = new StringBuilder();
        SAXBuilder builder = new SAXBuilder();
//        File xmlFile = new File("C:\\Users\\VI8G01R\\PETICION_DE_PRUEBA_ET.xml");
        File xmlFile = new File("C:\\Users\\VI8G01R\\PETICION_DE_PRUEBA_ET__completa.xml");

        System.out.println("Parsing FILE: " + xmlFile.getAbsolutePath());

        try {

            Document document = (Document) builder.build(xmlFile);
 
            Element rootNode = document.getRootElement();            
            Element nodeEvaluacionTramite = rootNode.getChild("Body",Namespace.getNamespace("http://schemas.xmlsoap.org/soap/envelope/")).getChild("evaluacionTramiteResponse").getChild("evaluacionTramite");
            
            Element nodeEjecucion = null;
            Element nodeDetalle = null;
            
//            StringBuilder respCredCheck 

            respCredCheck.append("---------------------------GENERAL Evaluación Trámite------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("ejecucion");
            respCredCheck.append("Nemónico: " + nodeEvaluacionTramite.getChildText("nemonico") + "\n");
            respCredCheck.append("Nombre Flujo: " + nodeEjecucion.getChildText("nombreFlujo") + "\n");
            respCredCheck.append("Traza Ejecución: " + nodeEjecucion.getChildText("trazaEjecucion") + "\n");
            respCredCheck.append("Clasif Buró Crédito: " + nodeEjecucion.getChildText("clasifBuroCredito") + "\n");
            respCredCheck.append("Clasif Móvil2000: " + nodeEjecucion.getChildText("clasifMovil2000") + "\n");
            respCredCheck.append("Clasif Anacr: " + nodeEjecucion.getChildText("clasifAnacr") + "\n");
            respCredCheck.append("Resp Lista Negra: " + nodeEjecucion.getChildText("respListaNegra") + "\n");
            respCredCheck.append("Clase Crédito: " + nodeEjecucion.getChildText("claseCredito") + "\n");
            respCredCheck.append("Tipo Cliente: " + nodeEjecucion.getChildText("tipoCliente") + "\n");
            respCredCheck.append("---------------------------Lista Negra------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("listaNegra").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("listaNegra").getChild("detalle");
            respCredCheck.append("Clave Acción LN: " + nodeEjecucion.getChildText("claveAccionLN") + "\n");
            respCredCheck.append("Descripcion Acción LN: " + nodeEjecucion.getChildText("descripcionAccionLN") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Histórico M2K------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("movilM2K").getChild("historicoM2K").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("movilM2K").getChild("historicoM2K").getChild("detalle");
            respCredCheck.append("Clasificación: " + nodeEjecucion.getChildText("clasificacion") + "\n");
            respCredCheck.append("Líneas Activas: " + nodeEjecucion.getChildText("lineasActivas") + "\n");
            respCredCheck.append("Líneas Canceladas: " + nodeEjecucion.getChildText("lineasCanceladas") + "\n");
            respCredCheck.append("Importe Total Lin Canceladas: " + nodeEjecucion.getChildText("importeTotalLinCanceladas") + "\n");
            respCredCheck.append("Importe Total Lin Activas: " + nodeEjecucion.getChildText("importeTotalLinActivas") + "\n");
            respCredCheck.append("Referencia Ctas Activas: " + nodeEjecucion.getChildText("referenciaCtasActivas") + "\n");
            respCredCheck.append("Referencia Ctas Caneladas: " + nodeEjecucion.getChildText("referenciaCtasCaneladas") + "\n");
            respCredCheck.append("Adeudo: " + nodeEjecucion.getChildText("adeudo") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Adeudo M2K------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("movilM2K").getChild("adeudoM2K").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("movilM2K").getChild("adeudoM2K").getChild("detalle");
            respCredCheck.append("Líneas Activas: " + nodeEjecucion.getChildText("lineasActivas") + "\n");
            respCredCheck.append("Líneas Canceladas: " + nodeEjecucion.getChildText("lineasCanceladas") + "\n");
            respCredCheck.append("Importe Total Lin Canceladas: " + nodeEjecucion.getChildText("importeTotalLinCanceladas") + "\n");
            respCredCheck.append("Importe Total Lin Activas: " + nodeEjecucion.getChildText("importeTotalLinActivas") + "\n");
            respCredCheck.append("Referencia Ctas Activas: " + nodeEjecucion.getChildText("referenciaCtasActivas") + "\n");
            respCredCheck.append("Referencia Ctas Caneladas: " + nodeEjecucion.getChildText("referenciaCtasCaneladas") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Reporte Bc------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("buroCredito").getChild("reporteBc").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("buroCredito").getChild("reporteBc").getChild("detalle");
            respCredCheck.append("Clave Clasificación Bc: " + nodeEjecucion.getChildText("claveClasificacionBc") + "\n");
            respCredCheck.append("Descrip Clasificación Bc: " + nodeEjecucion.getChildText("descripClasificacionBc") + "\n");
            respCredCheck.append("Numero Líneas: " + nodeEjecucion.getChildText("numeroLineas") + "\n");
            respCredCheck.append("Valor Icc: " + nodeEjecucion.getChildText("valorIcc") + "\n");
            respCredCheck.append("Valor Score: " + nodeEjecucion.getChildText("valorScore") + "\n");
            respCredCheck.append("Estatus Final: " + nodeEjecucion.getChildText("estatusFinal") + "\n");
            respCredCheck.append("Folio Bc: " + nodeEjecucion.getChildText("folioBc") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Id Provider Bc------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("buroCredito").getChild("idProviderBc").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("buroCredito").getChild("idProviderBc").getChild("detalle");
            respCredCheck.append("Clave Clasificación Bc: " + nodeEjecucion.getChildText("claveClasificacionBc") + "\n");
            respCredCheck.append("Descrip Clasificación Bc: " + nodeEjecucion.getChildText("descripClasificacionBc") + "\n");
            respCredCheck.append("Numero Líneas: " + nodeEjecucion.getChildText("numeroLineas") + "\n");
            respCredCheck.append("Valor Icc: " + nodeEjecucion.getChildText("valorIcc") + "\n");
            respCredCheck.append("Valor Score: " + nodeEjecucion.getChildText("valorScore") + "\n");
            respCredCheck.append("Estatus Final: " + nodeEjecucion.getChildText("estatusFinal") + "\n");
            respCredCheck.append("Folio Bc: " + nodeEjecucion.getChildText("folioBc") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Repo Bc Icc------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("buroCredito").getChild("repoBcIcc").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("buroCredito").getChild("repoBcIcc").getChild("detalle");
            respCredCheck.append("Clave Clasificación Bc: " + nodeEjecucion.getChildText("claveClasificacionBc") + "\n");
            respCredCheck.append("Descrip Clasificación Bc: " + nodeEjecucion.getChildText("descripClasificacionBc") + "\n");
            respCredCheck.append("Numero Líneas: " + nodeEjecucion.getChildText("numeroLineas") + "\n");
            respCredCheck.append("Valor Icc: " + nodeEjecucion.getChildText("valorIcc") + "\n");
            respCredCheck.append("Valor Score: " + nodeEjecucion.getChildText("valorScore") + "\n");
            respCredCheck.append("Estatus Final: " + nodeEjecucion.getChildText("estatusFinal") + "\n");
            respCredCheck.append("Folio Bc: " + nodeEjecucion.getChildText("folioBc") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Id Prov Bc Icc------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("buroCredito").getChild("idProvBcIcc").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("buroCredito").getChild("idProvBcIcc").getChild("detalle");
            respCredCheck.append("Clave Clasificación Bc: " + nodeEjecucion.getChildText("claveClasificacionBc") + "\n");
            respCredCheck.append("Descrip Clasificación Bc: " + nodeEjecucion.getChildText("descripClasificacionBc") + "\n");
            respCredCheck.append("Numero Líneas: " + nodeEjecucion.getChildText("numeroLineas") + "\n");
            respCredCheck.append("Valor Icc: " + nodeEjecucion.getChildText("valorIcc") + "\n");
            respCredCheck.append("Valor Score: " + nodeEjecucion.getChildText("valorScore") + "\n");
            respCredCheck.append("Estatus Final: " + nodeEjecucion.getChildText("estatusFinal") + "\n");
            respCredCheck.append("Folio Bc: " + nodeEjecucion.getChildText("folioBc") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Repo Bc Telco Icc------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("buroCredito").getChild("repoBcTelcoIcc").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("buroCredito").getChild("repoBcTelcoIcc").getChild("detalle");
            respCredCheck.append("Clave Clasificación Bc: " + nodeEjecucion.getChildText("claveClasificacionBc") + "\n");
            respCredCheck.append("Descrip Clasificación Bc: " + nodeEjecucion.getChildText("descripClasificacionBc") + "\n");
            respCredCheck.append("Numero Líneas: " + nodeEjecucion.getChildText("numeroLineas") + "\n");
            respCredCheck.append("Valor Icc: " + nodeEjecucion.getChildText("valorIcc") + "\n");
            respCredCheck.append("Valor Score: " + nodeEjecucion.getChildText("valorScore") + "\n");
            respCredCheck.append("Estatus Final: " + nodeEjecucion.getChildText("estatusFinal") + "\n");
            respCredCheck.append("Folio Bc: " + nodeEjecucion.getChildText("folioBc") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Id Prov Telco Icc------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("buroCredito").getChild("idProvTelcoIcc").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("buroCredito").getChild("idProvTelcoIcc").getChild("detalle");
            respCredCheck.append("Clave Clasificación Bc: " + nodeEjecucion.getChildText("claveClasificacionBc") + "\n");
            respCredCheck.append("Descrip Clasificación Bc: " + nodeEjecucion.getChildText("descripClasificacionBc") + "\n");
            respCredCheck.append("Numero Líneas: " + nodeEjecucion.getChildText("numeroLineas") + "\n");
            respCredCheck.append("Valor Icc: " + nodeEjecucion.getChildText("valorIcc") + "\n");
            respCredCheck.append("Valor Score: " + nodeEjecucion.getChildText("valorScore") + "\n");
            respCredCheck.append("Estatus Final: " + nodeEjecucion.getChildText("estatusFinal") + "\n");
            respCredCheck.append("Folio Bc: " + nodeEjecucion.getChildText("folioBc") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Buró Crédito Hst------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("buroCredito").getChild("buroCreditoHst").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("buroCredito").getChild("buroCreditoHst").getChild("detalle");
            respCredCheck.append("Producto: " + nodeEjecucion.getChildText("producto") + "\n");
            respCredCheck.append("Clave Clasificación Bc: " + nodeEjecucion.getChildText("claveClasificacionBc") + "\n");
            respCredCheck.append("Descrip Clasificación Bc: " + nodeEjecucion.getChildText("descripClasificacionBc") + "\n");
            respCredCheck.append("Numero Líneas: " + nodeEjecucion.getChildText("numeroLineas") + "\n");
            respCredCheck.append("Valor Icc: " + nodeEjecucion.getChildText("valorIcc") + "\n");
            respCredCheck.append("Valor Score: " + nodeEjecucion.getChildText("valorScore") + "\n");
            respCredCheck.append("Estatus Final: " + nodeEjecucion.getChildText("estatusFinal") + "\n");
            respCredCheck.append("Folio Bc: " + nodeEjecucion.getChildText("folioBc") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Buró Crédito Moral------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("buroCreditoMoral").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("buroCreditoMoral").getChild("detalle");
            respCredCheck.append("Clave Clasificación Bc: " + nodeEjecucion.getChildText("claveClasificacionBc") + "\n");
            respCredCheck.append("Descrip Clasificación Bc: " + nodeEjecucion.getChildText("descripClasificacionBc") + "\n");
            respCredCheck.append("Numero Líneas: " + nodeEjecucion.getChildText("numeroLineas") + "\n");
            respCredCheck.append("Valor Icc: " + nodeEjecucion.getChildText("valorIcc") + "\n");
            respCredCheck.append("Valor Score: " + nodeEjecucion.getChildText("valorScore") + "\n");
            respCredCheck.append("Estatus Final: " + nodeEjecucion.getChildText("estatusFinal") + "\n");
            respCredCheck.append("Folio Bc: " + nodeEjecucion.getChildText("folioBc") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Score CCS------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("scoreCCS").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("scoreCCS").getChild("detalle");
            respCredCheck.append("Clave Clase Crédito: " + nodeEjecucion.getChildText("claveClaseCredito") + "\n");
            respCredCheck.append("Descrip Clase Crédito: " + nodeEjecucion.getChildText("descripClaseCredito") + "\n");
            respCredCheck.append("Clave Clasificación Final: " + nodeEjecucion.getChildText("claveClasificacionFinal") + "\n");
            respCredCheck.append("Descrip Clasificación Final: " + nodeEjecucion.getChildText("descripClasificacionFinal") + "\n");
            respCredCheck.append("ClaveTipo Cliente: " + nodeEjecucion.getChildText("claveTipoCliente") + "\n");
            respCredCheck.append("Descrip Tipo Cliente: " + nodeEjecucion.getChildText("descripTipoCliente") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Gama Plan------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("gamaPlan").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("gamaPlan").getChild("detalle");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Depósito Renta------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("depositoRenta").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("depositoRenta").getChild("detalle");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Límite Crédito------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("limiteCredito").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("limiteCredito").getChild("detalle");
            respCredCheck.append("Límite Crédito: " + nodeEjecucion.getChildText("limiteCredito") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Financiamiento------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("financiamiento").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("financiamiento").getChild("detalle");
            respCredCheck.append("Aplica Financiamiento: " + nodeEjecucion.getChildText("aplicaFinanciamiento") + "\n");
            respCredCheck.append("Monto Enganche: " + nodeEjecucion.getChildText("montoEnganche") + "\n");
            respCredCheck.append("Monto Financiado: " + nodeEjecucion.getChildText("montoFinanciado") + "\n");
            respCredCheck.append("Monto Parcialidad: " + nodeEjecucion.getChildText("montoParcialidad") + "\n");
            respCredCheck.append("Monto SobrePrecio: " + nodeEjecucion.getChildText("montoSobrePrecio") + "\n");
            respCredCheck.append("Monto Total: " + nodeEjecucion.getChildText("montoTotal") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Cargo Interredes------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("cargoInterredes").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("cargoInterredes").getChild("detalle");
            respCredCheck.append("Ticket: " + nodeEjecucion.getChildText("ticket") + "\n");
            respCredCheck.append("IdCargo: " + nodeEjecucion.getChildText("idCargo") + "\n");
            respCredCheck.append("Primer Cargo: " + nodeEjecucion.getChildText("primerCargo") + "\n");
            respCredCheck.append("Segundo Cargo: " + nodeEjecucion.getChildText("segundoCargo") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Líneas Auto Admon------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("lineasAutorizadas").getChild("lineasAutoAdmon").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("lineasAutorizadas").getChild("lineasAutoAdmon").getChild("detalle");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Líneas Auto Edad------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("lineasAutorizadas").getChild("lineasAutoEdad").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("lineasAutorizadas").getChild("lineasAutoEdad").getChild("detalle");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Verificación Dom------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("verificacionDom").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("verificacionDom").getChild("detalle");
            respCredCheck.append("Clave Modalidad Invest: " + nodeEjecucion.getChildText("claveModalidadInvest") + "\n");
            respCredCheck.append("Descrip Modalidad Invest: " + nodeEjecucion.getChildText("descripModalidadInvest") + "\n");
            respCredCheck.append("Genera Verificación: " + nodeEjecucion.getChildText("generaVerificacion") + "\n");
            respCredCheck.append("Mensaje Verificación: " + nodeEjecucion.getChildText("mensajeVerificacion") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Anacr Adeudo------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("anacr").getChild("anacrAdeudo").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("anacr").getChild("anacrAdeudo").getChild("detalle");
            respCredCheck.append("Nemónico: " + nodeEvaluacionTramite.getChild("anacr").getChild("anacrAdeudo").getChildText("nemonico") + "\n");
            respCredCheck.append("Tiene Adeudo: " + nodeEjecucion.getChildText("tieneAdeudo") + "\n");
            respCredCheck.append("Adeudo Total Activo: " + nodeEjecucion.getChildText("adeudoTotalActivo") + "\n");
            respCredCheck.append("Adeudo Total Inactivo: " + nodeEjecucion.getChildText("adeudoTotalInactivo") + "\n");
            respCredCheck.append("Líneas Activas: " + nodeEjecucion.getChildText("lineasActivas") + "\n");
            respCredCheck.append("Líneas Canceladas: " + nodeEjecucion.getChildText("lineasCanceladas") + "\n");
            respCredCheck.append("Referencia Ctas Activas: " + nodeEjecucion.getChildText("referenciaCtasActivas") + "\n");
            respCredCheck.append("Referencia Ctas Canceladas: " + nodeEjecucion.getChildText("referenciaCtasCanceladas") + "\n");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------Anacr Hst------------------------------------\n");
            nodeEjecucion = nodeEvaluacionTramite.getChild("anacr").getChild("anacrHst").getChild("ejecucion");
            nodeDetalle = nodeEvaluacionTramite.getChild("anacr").getChild("anacrHst").getChild("detalle");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");
            respCredCheck.append("---------------------------GENERAL Evaluación Trámite respuesta------------------------------------\n");
            nodeDetalle = nodeEvaluacionTramite.getChild("detalle");
            respCredCheck.append("Acción Respuesta: " + nodeDetalle.getChildText("accionRespuesta") + "\n");
            respCredCheck.append("Mensaje: " + nodeDetalle.getChildText("mensaje") + "\n");
            respCredCheck.append("Tipo Respuesta: " + nodeDetalle.getChildText("tipoRespuesta") + "\n");

            

        } catch (IOException e) {
            System.out.println(e.getMessage());
        } catch (JDOMException e) {
            System.out.println(e.getMessage());
        }
        return respCredCheck.toString();
    }
}
