-------SEQUENCE_TT_WS_LLAMADA_RESPUESTA-------

CREATE SEQUENCE DBO.SEQUENCE_TT_WS_LLAMADA_RESPUESTA AS INT START WITH 1 INCREMENT BY 1 MAXVALUE 2147483647 NO CACHE;

-------TC_SISTEMAS-------

CREATE TABLE dbo.TC_SISTEMAS(
	CLAVE smallint,
	SISTEMA varchar(30),
 CONSTRAINT PK_TC_SISTEMAS PRIMARY KEY (CLAVE)
);

INSERT INTO dbo.TC_SISTEMAS(CLAVE,SISTEMA) VALUES (1,'CREDIT CHECK');
INSERT INTO dbo.TC_SISTEMAS(CLAVE,SISTEMA) VALUES (2,'SAFIN');

-------TT_WS_LLAMADA_RESPUESTA-------

CREATE TABLE DBO.TT_WS_LLAMADA_RESPUESTA
(
    ID INT DEFAULT (NEXT VALUE FOR DBO.SEQUENCE_TT_WS_LLAMADA_RESPUESTA),
	CLAVE_SISTEMA smallint,
    LLAMADA varchar(4600),
	RESPUESTA text,
	USUARIO varchar(15),
	FECHA datetime,
	CONSTRAINT PK_TT_LLAMADA_RESPUESTA PRIMARY KEY (ID)
);

-------TC_SISTEMAS_CATALOGOS-------

CREATE TABLE dbo.TC_SISTEMAS_CATALOGOS(
	CLAVE_SISTEMA smallint,
	CAMPO varchar(30),
	CLAVE_VALOR	nvarchar(15),
	VALOR nvarchar(50)
 CONSTRAINT PK_TC_CATALOGOS PRIMARY KEY (CLAVE_SISTEMA,CAMPO,CLAVE_VALOR)
);

--INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'','','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'CREDITO_AUTOMOTRIZ','V','Si tiene cuenta automotriz');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'CREDITO_AUTOMOTRIZ','F','No tiene cuenta automotriz');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'CREDITO_BANCARIO','V','Si tiene cuenta bancaria');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'CREDITO_BANCARIO','F','No tiene cuenta bancaria');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'TIPO_LINEA','D','DATOS');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'TIPO_LINEA','V','VOZ');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'TIPO_PLAN','N','NORMAL');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'TIPO_PLAN','M','MIXTO');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'TIPO_TRAMITE','ACT','ACTIVACION');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'TIPO_TRAMITE','SW','CAMBIO DE EQUIPO');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'FORMA_PAGO','CC','DOMICILIACION');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'FORMA_PAGO','EF','EFECTIVO');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'FORMA_PAGO','TC','TARJETA DE CREDITO');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'MERCADO','M','MASIVO');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'MERCADO','C','CORPORATIVO');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'MERCADO','P','PYME');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'SEXO','M','Hombre');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'SEXO','F','Mujer');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'CLAVE_BANCO','AMEX','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'CLAVE_BANCO','BMER','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'CLAVE_BANCO','BMEX','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'CLAVE_BANCO','CNET','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'CLAVE_BANCO','INTR','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'CLAVE_BANCO','SEAR','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'CLAVE_BANCO','SNBR','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'VENTA_PLAZOS','SI','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'VENTA_PLAZOS','NO','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'PROYECTO','VENTA EN LINEA','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'PROYECTO','TELMEX','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'PROYECTO','COPPEL','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'TIPO_PERSONA','FISICA','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'TIPO_PERSONA','MORAL','');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'MODALIDAD_INVESTIGACION','IN','INMEDIATA');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'MODALIDAD_INVESTIGACION','DI','DIFERIDA');
INSERT INTO dbo.TC_SISTEMAS_CATALOGOS(CLAVE_SISTEMA,CAMPO,CLAVE_VALOR,VALOR) VALUES (1,'MODALIDAD_INVESTIGACION','NA','N/A');

-------TC_MARCA-------

CREATE TABLE dbo.TC_MARCA(
	ID smallint NOT NULL,
	CLAVE varchar(30),
	DESCRIPCION nvarchar(220),
	DISPO_DEUR char(1),
	DISPO_R9 char(1),
	NOMBRE nvarchar(90) NULL,
 CONSTRAINT PK_TC_MARCA PRIMARY KEY (ID) 
);

-------TC_MODELO-------

CREATE TABLE dbo.TC_MODELO(
	ID smallint NOT NULL,
	ID_MARCA smallint NOT NULL,
	CLAVE_M2K varchar(30),
	DESCRIPCION nvarchar(70) NULL,
	NOMBRE nvarchar(70) NULL,
	DISPO_DEUR char(1),
	DISPO_R9 char(1),
	CONSTRAINT PK_TC_MODELO PRIMARY KEY (ID),
	CONSTRAINT FK_TC_MODELO FOREIGN KEY (ID_MARCA) REFERENCES dbo.TC_MARCA(ID)
);

-------TC_TIPO_PLAZO-------

CREATE TABLE dbo.TC_TIPO_PLAZO(
	CLAVE char(1),
	PLAZO varchar(30),
 CONSTRAINT PK_TC_TIPO_PLAZO PRIMARY KEY (CLAVE)
);

INSERT INTO dbo.TC_TIPO_PLAZO(CLAVE,PLAZO) VALUES ('L','LIBRE');
INSERT INTO dbo.TC_TIPO_PLAZO(CLAVE,PLAZO) VALUES ('F','FORZOSO');

-------TC_PLAN-------

CREATE TABLE dbo.TC_PLAN(
	ID int NOT NULL,
	CLAVE_M2K varchar(10) NOT NULL,
	CLAVE_GRUPO nvarchar(100) NULL,
	NOMBRE nvarchar(100) NULL,
	DISPO_DEUR char(1),
	DISPO_R9 char(1),
	TIPO_PLAZO char(1),
	CONSTRAINT PK_TC_PLAN PRIMARY KEY (ID),
	CONSTRAINT FK_TC_PLAN FOREIGN KEY (TIPO_PLAZO) REFERENCES dbo.TC_TIPO_PLAZO(CLAVE)
);



