-------TC_SAFIN_TIPOS_PRODUCTO-------

CREATE TABLE dbo.TC_SAFIN_TIPOS_PRODUCTO(
	CLAVE smallint,
	PRODUCTO varchar(10),
 CONSTRAINT PK_TC_SAFIN_TIPOS_PRODUCTO PRIMARY KEY (CLAVE)
);

INSERT INTO dbo.TC_SAFIN_TIPOS_PRODUCTO(CLAVE,PRODUCTO) VALUES (1,'EQUIPO');
INSERT INTO dbo.TC_SAFIN_TIPOS_PRODUCTO(CLAVE,PRODUCTO) VALUES (2,'ACCESORIO');
INSERT INTO dbo.TC_SAFIN_TIPOS_PRODUCTO(CLAVE,PRODUCTO) VALUES (3,'SERVICIO');

-------TC_SAFIN_SISTEMAS-------

CREATE TABLE dbo.TC_SAFIN_SISTEMAS(
	CLAVE smallint,
	SISTEMA varchar(15),
 CONSTRAINT PK_TC_SAFIN_SISTEMAS PRIMARY KEY (CLAVE)
);

INSERT INTO dbo.TC_SAFIN_SISTEMAS(CLAVE,SISTEMA) VALUES (1,'SISACT');
INSERT INTO dbo.TC_SAFIN_SISTEMAS(CLAVE,SISTEMA) VALUES (2,'ECAC');
INSERT INTO dbo.TC_SAFIN_SISTEMAS(CLAVE,SISTEMA) VALUES (3,'SICORE');
INSERT INTO dbo.TC_SAFIN_SISTEMAS(CLAVE,SISTEMA) VALUES (4,'SAFIN');
INSERT INTO dbo.TC_SAFIN_SISTEMAS(CLAVE,SISTEMA) VALUES (5,'SMART');
INSERT INTO dbo.TC_SAFIN_SISTEMAS(CLAVE,SISTEMA) VALUES (6,'CREDIT CHECK');

-------TC_SAFIN_MERCADOS-------

CREATE TABLE dbo.TC_SAFIN_MERCADOS(
	CLAVE smallint,
	MERCADO varchar(15),
 CONSTRAINT PK_TC_SAFIN_MERCADOS PRIMARY KEY (CLAVE)
);

INSERT INTO dbo.TC_SAFIN_MERCADOS(CLAVE,MERCADO) VALUES (1,'MASIVO');
INSERT INTO dbo.TC_SAFIN_MERCADOS(CLAVE,MERCADO) VALUES (2,'PYME');
INSERT INTO dbo.TC_SAFIN_MERCADOS(CLAVE,MERCADO) VALUES (3,'CORPORATIVO');

-------TC_SAFIN_MOVIMIENTOS-------

CREATE TABLE dbo.TC_SAFIN_MOVIMIENTOS(
	CLAVE smallint,
	MOVIMIENTO varchar(15),
 CONSTRAINT PK_TC_SAFIN_MOVIMIENTOS PRIMARY KEY (CLAVE)
);

INSERT INTO dbo.TC_SAFIN_MOVIMIENTOS(CLAVE,MOVIMIENTO) VALUES (1,'ACTIVACIÓN');
INSERT INTO dbo.TC_SAFIN_MOVIMIENTOS(CLAVE,MOVIMIENTO) VALUES (2,'RENOVACIÓN');
INSERT INTO dbo.TC_SAFIN_MOVIMIENTOS(CLAVE,MOVIMIENTO) VALUES (3,'MIGRACIÓN');
INSERT INTO dbo.TC_SAFIN_MOVIMIENTOS(CLAVE,MOVIMIENTO) VALUES (4,'PORTABILIDAD');

-------TC_SAFIN_CANALES-------

CREATE TABLE dbo.TC_SAFIN_CANALES(
	CLAVE smallint,
	CANAL varchar(15),
 CONSTRAINT PK_TC_SAFIN_CANALES PRIMARY KEY (CLAVE)
);

INSERT INTO dbo.TC_SAFIN_CANALES(CLAVE,CANAL) VALUES (1,'DAT');
INSERT INTO dbo.TC_SAFIN_CANALES(CLAVE,CANAL) VALUES (2,'CAC');
INSERT INTO dbo.TC_SAFIN_CANALES(CLAVE,CANAL) VALUES (3,'TELEFÓNICO');

-------TC_SAFIN_FORMAS_PAGO-------

CREATE TABLE dbo.TC_SAFIN_FORMAS_PAGO(
	CLAVE char(3),
	FORMA_PAGO varchar(25),
 CONSTRAINT PK_TC_SAFIN_FORMAS_PAGO PRIMARY KEY (CLAVE)
);

INSERT INTO dbo.TC_SAFIN_FORMAS_PAGO(CLAVE,FORMA_PAGO) VALUES ('EF','Efectivo');
INSERT INTO dbo.TC_SAFIN_FORMAS_PAGO(CLAVE,FORMA_PAGO) VALUES ('TC','Tarjeta de crédito');
INSERT INTO dbo.TC_SAFIN_FORMAS_PAGO(CLAVE,FORMA_PAGO) VALUES ('TI','Efectivo');
INSERT INTO dbo.TC_SAFIN_FORMAS_PAGO(CLAVE,FORMA_PAGO) VALUES ('CC','Domiciliado');

